kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-gitops

bases:
  - ../../../03-cluster-services/00-developer-gitops
  #- ../../../03-cluster-services/10-logging
  - ../../../03-cluster-services/11-cicd-tools
  - ../../../03-cluster-services/12-image-registry
  #- ../../../03-cluster-services/13-gitbucket
  #- ../../../03-cluster-services/14-gogs
  #- ../../../03-cluster-services/01-sealed-secrets
  #- ../../../03-cluster-services/02-openshift-pipelines
  #- ../../../03-cluster-services/03-web-terminal
  #- ../../../03-cluster-services/04-amq-streams
  - ../../../03-cluster-services/05-single-sign-on
  #- ../../../03-cluster-services/06-workload-monitoring
  #- ../../../03-cluster-services/07-compliance
  #- ../../../03-cluster-services/08-advanced-cluster-security
  #- ../../../03-cluster-services/09-storage

resources:
  - cluster-services-project.yaml
